# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

[package]
name = "postgres"
version = "0.1.0"
kind = "static-library"
entry = "src/lib.rz"

[dependencies]
crypto = "../crypto"

[profile.debug]
optimization = 0
debug = true
incremental = true

[profile.release]
optimization = 3
debug = false
incremental = true
