[workspace]
members = [
    "crypto",
    "serde",
    "toml",
    "regex",
    "uuid",
    "semver",
    "datetime",
    "websocket",
    "http-router",
    "sqlite",
    "postgres",
    "jwt",
    "multipart",
    "archive",
    "testing",
]
