# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

[package]
name = "sqlite"
version = "0.3.0"
kind = "static-library"
entry = "src/lib.rz"

[dependencies]
alloc = "../../../raz/library/packages/alloc"
core = "../../../raz/library/packages/core"

[native]
libraries = ["sqlite3"]

[profile.debug]
optimization = 0
debug = true
incremental = true

[profile.release]
optimization = 3
debug = false
incremental = true
